apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  selector:
    app: shopping
  type: LoadBalancer  # Change from NodePort to LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

